'use client';

// Cmd/Ctrl-K search modal. Fuzzy match against build-time index at
// /docs/search-index.json. The index is generated by
// scripts/build-docs-index.ts during the prebuild step.

import { useEffect, useMemo, useState, useRef } from 'react';
import Link from 'next/link';

interface SearchEntry {
  path: string;
  title: string;
  section: string;
  anchor: string;
  snippet: string;
}

const RECENT_KEY = 'tp_docs_recent';

export function DocsSearch() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [entries, setEntries] = useState<SearchEntry[]>([]);
  const [highlight, setHighlight] = useState(0);
  const [recent, setRecent] = useState<string[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);

  // Bind ⌘K / Ctrl-K + Esc.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      const isMod = e.metaKey || e.ctrlKey;
      if (isMod && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setOpen((v) => !v);
      } else if (e.key === 'Escape' && open) {
        setOpen(false);
      }
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  // Lazy-load the index on first open.
  useEffect(() => {
    if (!open || entries.length > 0) return;
    fetch('/docs/search-index.json')
      .then((r) => (r.ok ? r.json() : []))
      .then((data) => Array.isArray(data) && setEntries(data))
      .catch(() => setEntries([]));
    try {
      const stored = localStorage.getItem(RECENT_KEY);
      // Hydrating client-only recent-searches list from localStorage on
      // first open. Cascading render is intentional.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      if (stored) setRecent(JSON.parse(stored));
    } catch {
      /* ignore */
    }
  }, [open, entries.length]);

  // Autofocus on open.
  useEffect(() => {
    if (open) inputRef.current?.focus();
  }, [open]);

  const results = useMemo(() => {
    if (!query.trim()) return entries.slice(0, 8);
    const q = query.toLowerCase();
    return entries
      .map((e) => ({
        e,
        score: scoreEntry(e, q),
      }))
      .filter((r) => r.score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, 8)
      .map((r) => r.e);
  }, [query, entries]);

  function pickRecent(value: string) {
    setRecent((prev) => {
      const next = [value, ...prev.filter((v) => v !== value)].slice(0, 5);
      try {
        localStorage.setItem(RECENT_KEY, JSON.stringify(next));
      } catch {
        /* ignore */
      }
      return next;
    });
  }

  function navigate(entry: SearchEntry) {
    pickRecent(`${entry.title} · ${entry.section}`);
    setOpen(false);
    setQuery('');
    window.location.href = `${entry.path}${entry.anchor}`;
  }

  function onKeyDownInput(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setHighlight((h) => Math.min(results.length - 1, h + 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setHighlight((h) => Math.max(0, h - 1));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const pick = results[highlight];
      if (pick) navigate(pick);
    }
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Search docs"
        className="docs-search-trigger mono"
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: 10,
          padding: '8px 12px',
          fontSize: 12,
          letterSpacing: '0.04em',
          color: 'var(--ink-3)',
          background: 'var(--paper-2)',
          border: '1px solid var(--border)',
          borderRadius: 4,
          cursor: 'pointer',
          marginBottom: 18,
        }}
      >
        <span>Search the docs</span>
        <kbd
          style={{
            fontFamily: 'var(--font-mono), monospace',
            fontSize: 10,
            padding: '2px 5px',
            background: 'var(--paper)',
            border: '1px solid var(--border)',
            borderRadius: 3,
            color: 'var(--muted)',
          }}
        >
          ⌘ K
        </kbd>
      </button>

      {open ? (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Search docs"
          onClick={() => setOpen(false)}
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(20, 19, 15, 0.5)',
            backdropFilter: 'blur(4px)',
            zIndex: 1000,
            display: 'flex',
            justifyContent: 'center',
            paddingTop: '12vh',
          }}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              width: 'min(560px, 92vw)',
              maxHeight: '70vh',
              display: 'flex',
              flexDirection: 'column',
              background: 'var(--paper)',
              border: '1px solid var(--ink)',
              borderRadius: 4,
              boxShadow: '0 24px 48px rgba(0,0,0,0.18)',
              overflow: 'hidden',
            }}
          >
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                padding: '14px 16px',
                borderBottom: '1px solid var(--border)',
              }}
            >
              <span aria-hidden style={{ fontSize: 16, color: 'var(--muted)' }}>
                ⌕
              </span>
              <input
                ref={inputRef}
                type="text"
                value={query}
                onChange={(e) => {
                  setQuery(e.target.value);
                  setHighlight(0);
                }}
                onKeyDown={onKeyDownInput}
                placeholder="Search pages, sections, code…"
                style={{
                  flex: 1,
                  background: 'transparent',
                  border: 'none',
                  outline: 'none',
                  fontSize: 16,
                  color: 'var(--ink)',
                }}
                autoFocus
              />
              <kbd
                style={{
                  fontFamily: 'var(--font-mono), monospace',
                  fontSize: 10,
                  padding: '2px 6px',
                  background: 'var(--paper-2)',
                  border: '1px solid var(--border)',
                  borderRadius: 3,
                  color: 'var(--muted)',
                }}
              >
                Esc
              </kbd>
            </div>
            <div style={{ flex: 1, overflowY: 'auto', padding: 8 }}>
              {!query && recent.length > 0 ? (
                <div
                  className="mono"
                  style={{
                    fontSize: 10,
                    letterSpacing: '0.16em',
                    textTransform: 'uppercase',
                    color: 'var(--muted)',
                    padding: '6px 12px',
                  }}
                >
                  Recent
                </div>
              ) : null}
              {!query && recent.length > 0
                ? recent.map((r) => (
                    <div
                      key={r}
                      style={{
                        padding: '8px 12px',
                        fontSize: 13,
                        color: 'var(--ink-3)',
                      }}
                    >
                      {r}
                    </div>
                  ))
                : null}

              {results.length === 0 && entries.length > 0 ? (
                <div
                  style={{
                    padding: 24,
                    textAlign: 'center',
                    fontSize: 13,
                    color: 'var(--muted)',
                  }}
                >
                  No matches for &ldquo;{query}&rdquo;
                </div>
              ) : null}

              {entries.length === 0 ? (
                <div
                  style={{
                    padding: 24,
                    textAlign: 'center',
                    fontSize: 12,
                    color: 'var(--muted)',
                    lineHeight: 1.5,
                  }}
                >
                  Search index not built yet. Run{' '}
                  <code className="mono">pnpm build</code> to generate it.
                </div>
              ) : null}

              {results.map((e, i) => (
                <button
                  type="button"
                  key={`${e.path}${e.anchor}`}
                  onClick={() => navigate(e)}
                  onMouseEnter={() => setHighlight(i)}
                  style={{
                    display: 'block',
                    width: '100%',
                    textAlign: 'left',
                    padding: '10px 12px',
                    border: 'none',
                    borderRadius: 4,
                    background: i === highlight ? 'var(--paper-2)' : 'transparent',
                    cursor: 'pointer',
                    color: 'inherit',
                  }}
                >
                  <div
                    className="mono"
                    style={{
                      fontSize: 10,
                      letterSpacing: '0.08em',
                      textTransform: 'uppercase',
                      color: 'var(--muted)',
                    }}
                  >
                    {e.title} ›
                  </div>
                  <div style={{ fontSize: 14, color: 'var(--ink)', fontWeight: 600 }}>
                    {e.section}
                  </div>
                  <div
                    style={{
                      fontSize: 12,
                      color: 'var(--ink-3)',
                      lineHeight: 1.4,
                      marginTop: 2,
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                      display: '-webkit-box',
                      WebkitLineClamp: 2,
                      WebkitBoxOrient: 'vertical',
                    }}
                  >
                    {e.snippet}
                  </div>
                </button>
              ))}
            </div>
            <div
              className="mono"
              style={{
                padding: '10px 16px',
                fontSize: 10,
                letterSpacing: '0.06em',
                color: 'var(--muted)',
                borderTop: '1px solid var(--border)',
                background: 'var(--paper-2)',
                display: 'flex',
                gap: 16,
                justifyContent: 'space-between',
              }}
            >
              <span>↑↓ navigate · Enter open</span>
              <Link href="/docs" style={{ color: 'var(--ink-3)', textDecoration: 'none' }}>
                All docs →
              </Link>
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
}

function scoreEntry(e: SearchEntry, q: string): number {
  const title = e.title.toLowerCase();
  const section = e.section.toLowerCase();
  const snippet = e.snippet.toLowerCase();
  let score = 0;
  if (title.includes(q)) score += 5;
  if (section.includes(q)) score += 4;
  if (snippet.includes(q)) score += 2;
  // Word-prefix bonus.
  const words = q.split(/\s+/);
  for (const w of words) {
    if (!w) continue;
    if (title.startsWith(w)) score += 1;
    if (section.startsWith(w)) score += 1;
  }
  return score;
}
